# Generated by Django 3.0.7 on 2020-07-19 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200717_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_posted']},
        ),
    ]
