# Generated by Django 3.0.8 on 2020-07-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200721_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoption',
            name='clicked_value',
            field=models.IntegerField(null=True),
        ),
    ]
