# Generated by Django 3.0.8 on 2020-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200721_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postoption',
            name='clicked_value',
            field=models.IntegerField(default=0),
        ),
    ]
