# Generated by Django 3.0.8 on 2020-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200721_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoption',
            name='clicked_percent',
            field=models.IntegerField(default=0),
        ),
    ]
