# Generated by Django 3.0.8 on 2020-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200801_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='post',
            name='verification',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declied'), ('pending', 'pending')], default='accepted', max_length=150),
        ),
    ]
