# Generated by Django 3.0.8 on 2020-07-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planner',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AlterModelTable(
            name='planner',
            table='planner',
        ),
    ]
