# Generated by Django 3.0.8 on 2020-07-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20200729_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planner',
            name='content',
        ),
    ]
