# Generated by Django 3.0.8 on 2020-07-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_planner_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planner',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
