# Generated by Django 3.0.8 on 2020-09-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20200729_1249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planner',
            table='Planner',
        ),
    ]
